### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by Kalugin-Roman** [ProfessorNavigator/mylibrary#2]
Is it possible to compile the Flatpak version? It lacks the ability to easily and quickly launch.
Thanks for the answer!

**Comment by ProfessorNavigator** [comment]
Short answer is "no". Because of glibc versions and other possibly library conflicts. The same is regarding appimage and snap.

**Comment by ProfessorNavigator** [comment]
> What glibc issues are you talking about? Flatpak is supposed to be free of them

Only "supposed". Your application cannot work without interaction with kernel API. Even if it is not used in code directly. And kernel API means interaction with glibc. So you cannot avoid issues about improper versions of glibc without any special tricks. But such tricks may (actually not 'may', but 'will') have unpredictable consequences. Not only for application work, but for whole system. And, by the way, glibc is used not only by kernel, but also for example in GTK (actually in all C-language based applications, in many C++ based, and in some other). So, only way to use applications correctly is to build them from sources (ideally - for each machine, "practically" - it is sufficient to build for each distro once in form of package).

**Comment by ProfessorNavigator** [comment]
> I think you slightly misunderstand how Flatpak works. You build for Flatpak once from sources, your app will depend on glibc provided by Flatpak runtime and work on most Linux distros. Same with snaps but not AppImages

Even if flatpak or snap provides there own "versions" of glibc, it is not actually a real glibc, only some kind of calls translation library. Like wine. There is no magic in this world. Any application need to interact with system kernel, even if it is inside of some kind of container. System kernel based on glibc. On version it has been compiled by. That is all. Any flatpak application needs flatpak based components, which were compiled by your system native libraries. So, why to use "middleman" with its own errors, if you can act directly? Only real cause - your own laziness. You do not want to learn how to build applications from sources. I cannot accept it. And will not. So - no any "official" flatpaks, snaps or appimages. It is my official position, and I doubt, that you will find any arguments to change it.

**Comment by ProfessorNavigator** [comment]
> ok. the reason isn't glibc, but your own preferences

Yes, but not only. If you do not believe me, you can try to build flatpak from any application on your own and to deploy it for several different distros then (not different versions of for example Ubuntu, but on really different distros). I suppose, quantity of bugs will impress you. And do not forget, that flatpak is actually container, so disk space consumption, memory consumption, processor time consumption... Also bare in mind that  for example MyLibrary can use seven hundreds megabytes of memory or even more on its own. And same is regarding CPU load consumption. On high load collection creation operations and so on.

**Comment by faveoled** [comment]
> Yes, but not only. If you do not believe me, you can try to build flatpak from any application on your own and to deploy it for several different distros then (not different versions of for example Ubuntu, but on really different distros).

Native builds are event worse in that regard
