### ISSUE TITLE
[feature] Please consider adding filename pattern while saving books from library.

### ISSUE THREAD

**Issue by ioctl-user** [ProfessorNavigator/mylibrary#3]
There is a following suggestion: add an option to save books from library according to user defined or predefined pattern.

For example, to save books with make like this: "Authors. Book_name.file_extension" .

**Comment by ProfessorNavigator** [comment]
The reason why it has not been done yet is the following: not all e-books are designed well. Some books does not even have completed "Author" field or title. Especially in .pdf and .djvu files. So the best variant in this situation in my opinion is to use file names only. But anyway you can rename the file in any way you want while save it - proper file save dialog allows it.

**Comment by ioctl-user** [comment]
Is this possible to add additional option along with the default one to save files, that has all needed requisites?

**Comment by ProfessorNavigator** [comment]
I cannot promise, but I ill see, what can I do. This issue will be left opened and I will write here on any result - positive or negative. And I am sorry in advance for any delay - unfortunately I do not have enough time to deal with this project (but any way it is not left unsupported, work in progress).

**Comment by ProfessorNavigator** [comment]
https://github.com/ProfessorNavigator/mylibrary/releases/tag/v2.2

**Comment by ioctl-user** [comment]
Thanks!
